In [1]:
import pandas as pd
import numpy as np
import sklearn
from sklearn import datasets

In [2]:
#Loading the Dataset:
iris = datasets.load_iris()
X = iris.data
Y = iris.target


In [3]:
#Visualizing the Dataset:
iris.target_names
iris.feature_names
iris.data[0:5]


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [4]:
#Splitting the Dataset:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3)

In [5]:
#Building the AdaBoost Model:
from sklearn.ensemble import AdaBoostClassifier
adb = AdaBoostClassifier()
model = adb.fit(X_train, Y_train)
y_pred = model.predict(X_test)
y_pred


array([2, 0, 2, 0, 0, 0, 1, 1, 0, 0, 1, 2, 1, 0, 1, 1, 0, 2, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 2, 1, 0, 0, 0, 1, 1, 1, 2, 1, 1, 1, 2, 1, 0, 2, 0,
       2])

In [6]:
#Evaluating the Model
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(Y_test, y_pred))
print(classification_report(Y_test, y_pred))
print(accuracy_score(Y_test, y_pred))


[[16  0  0]
 [ 0 19  1]
 [ 0  1  8]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       0.95      0.95      0.95        20
           2       0.89      0.89      0.89         9

    accuracy                           0.96        45
   macro avg       0.95      0.95      0.95        45
weighted avg       0.96      0.96      0.96        45

0.9555555555555556


In [7]:
"Using SVM as a base estimator"""
from sklearn.svm import SVC
from sklearn.ensemble import AdaBoostClassifier
svc = SVC(probability = True, kernel='linear')
adb = AdaBoostClassifier(n_estimators=100,base_estimator = svc, learning_rate= 0.01)

In [8]:
#Training and Predicting the AdaBoost Classifier
model = adb.fit(X_train, Y_train)
y_pred = model.predict(X_test)
y_pred


/usr/local/lib/python3.9/dist-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(


array([2, 0, 2, 0, 0, 0, 1, 2, 0, 0, 1, 2, 1, 0, 2, 1, 0, 2, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 2, 1, 0, 0, 0, 1, 1, 1, 2, 1, 1, 1, 2, 1, 0, 2, 0,
       2])

In [9]:
#Evaluating the Model:
print(confusion_matrix(Y_test, y_pred))
print(classification_report(Y_test, y_pred))
print(accuracy_score(Y_test, y_pred))

[[16  0  0]
 [ 0 18  2]
 [ 0  0  9]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      0.90      0.95        20
           2       0.82      1.00      0.90         9

    accuracy                           0.96        45
   macro avg       0.94      0.97      0.95        45
weighted avg       0.96      0.96      0.96        45

0.9555555555555556
